[plugins.kotlin]
id = "org.jetbrains.kotlin.multiplatform"
version = "1.7.10"

[plugins.ktlint]
id = "org.jlleitschuh.gradle.ktlint"
version = "10.3.0"

[plugins.detekt]
id = "io.gitlab.arturbosch.detekt"
version = "1.21.0"
